geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from geekshop import settings
from django.conf.urls.static import static

from products.views import ProductsIndexView

urlpatterns = [
    path('', ProductsIndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('userAdmin/', include('userAdmin.urls', namespace='userAdmin')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

userAdmin/urls.py
from django.urls import path
from userAdmin.views import index, UserAdminCreateView, UserAdminListView, UserAdminUpdateView, UserAdminDeleteView, \
    ProductsAdminListView, ProductsAdminCreateView, ProductsAdminUpdateView, CategoryAdminUpdateView, \
    CategoryAdminCreateView, CategoryAdminListView, ProductsAdminDeleteView, CategoryAdminDeleteView, \
    OrdersAdminListView, OrdersAdminCreateView, OrdersAdminUpdateView, OrdersAdminDeleteView

app_name = 'userAdmin'

urlpatterns = [
    path('', index, name='index'),

    path('orders/', OrdersAdminListView.as_view(), name='orders_read'),
    path('orders/create/', OrdersAdminCreateView.as_view(), name='orders_create'),
    path('orders/update_order/<int:pk>/', OrdersAdminUpdateView.as_view(), name='orders_update'),
    path('orders/delete_order/<int:pk>/', OrdersAdminDeleteView.as_view(), name='orders_delete'),

    path('users/', UserAdminListView.as_view(), name='users_read'),
    path('users/create/', UserAdminCreateView.as_view(), name='create_user'),
    path('users/update_user/<int:pk>/', UserAdminUpdateView.as_view(), name='update_user'),
    path('users/delete_user/<int:pk>/', UserAdminDeleteView.as_view(), name='delete_user'),

    path('products/', ProductsAdminListView.as_view(), name='products_read'),
    path('products/create/', ProductsAdminCreateView.as_view(), name='products_create'),
    path('products/update/<int:pk>/', ProductsAdminUpdateView.as_view(), name='products_update'),
    path('products/delete/<int:pk>/', ProductsAdminDeleteView.as_view(), name='products_delete'),

    path('category/', CategoryAdminListView.as_view(), name='category_read'),
    path('category/create/', CategoryAdminCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryAdminUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryAdminDeleteView.as_view(), name='category_delete'),
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserCreateView, profile, verify
# from users.views import UserProfileView

app_name = 'users'

urlpatterns = [
    path('', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('profile/', profile, name='profile'),
    # path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

orders/models.py
from django.conf import settings
from django.db import models

from products.models import Products


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='пользователь'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='создан'
    )

    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='обновлен'
    )
    status = models.CharField(
        max_length=3,
        choices=ORDER_STATUS_CHOICES,
        default=FORMING,
        verbose_name='статус'
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='активен'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.id}'

    def delete(self):
        items = self.order_items.select_related('product')
        for item in items:
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    def get_total_cost(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='order_items',
        verbose_name='заказ'
    )
    product = models.ForeignKey(
        Products,
        on_delete=models.CASCADE,
        verbose_name='продукт')

    quantity = models.PositiveIntegerField(
        default=0,
        verbose_name='количество'
    )

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    def __str__(self):
        return self.product.name

products/models.py
from django.db import models


class ProductsCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(blank=False, default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Products(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductsCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(blank=False, default=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


    def __str__(self):
        return f'{self.name}'

    @staticmethod
    def get_items():
        # return Products.objects.filter(is_active=True).order_by('category', 'name')
        return Products.objects.order_by('category', 'name')

userAdmin/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.db.models import F

from orders.models import Order
from products.models import Products, ProductsCategory
from users.models import User
from userAdmin.forms import AdminUserRegistrationForm, AdminUserUpdateForm, ProductCreateForm, ProductUpdateForm, \
    CategoryCreateForm, CategoryUpdateForm, OrdersCreateForm, OrdersUpdateForm


@user_passes_test(lambda u: u.is_staff)
def index(request):
    return render(request, 'userAdmin/index.html')


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


# Отображение и редактирование пользователей
class UserAdminListView(ListView):
    model = User
    template_name = 'userAdmin/userAdmin-read.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Пользователи'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserAdminCreateView(CreateView):
    model = User
    form_class = AdminUserRegistrationForm
    template_name = 'userAdmin/userAdmin-create.html'
    success_url = reverse_lazy('userAdmin:users_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Создание пользователя'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserAdminUpdateView(UpdateView):
    model = User
    form_class = AdminUserUpdateForm
    template_name = 'userAdmin/userAdmin-update-delete.html'
    success_url = reverse_lazy('userAdmin:users_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Редактирование пользователя'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserAdminDeleteView(DeleteView):
    model = User
    template_name = 'userAdmin/userAdmin-update-delete.html'
    success_url = reverse_lazy('userAdmin:users_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# Отображение и редактирование товаров
class ProductsAdminListView(LoginRequiredMixin, ListView):
    model = Products
    extra_context = {'title': 'Админ-панель - Товары'}
    template_name = 'userAdmin/products-list.html'

    def get_queryset(self):
        return Products.objects.all()


class ProductsAdminCreateView(CreateView):
    model = Products
    form_class = ProductCreateForm
    template_name = 'userAdmin/products-create.html'
    success_url = reverse_lazy('userAdmin:AdminOrdersList')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Создание товара'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductsAdminUpdateView(UpdateView):
    model = Products
    form_class = ProductUpdateForm
    template_name = 'userAdmin/products-update-delete.html'
    success_url = reverse_lazy('userAdmin:products_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Редактирование товара'

        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductsAdminDeleteView(DeleteView):
    model = Products
    template_name = 'userAdmin/products-update-delete.html'
    success_url = reverse_lazy('userAdmin:products_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# Отображение и редактирование категорий
class CategoryAdminListView(ListView):
    model = ProductsCategory
    extra_context = {'title': 'Админ-панель - Категории'}
    template_name = 'userAdmin/category-list.html'

    def get_queryset(self):
        return ProductsCategory.objects.all()


class CategoryAdminCreateView(CreateView):
    model = ProductsCategory
    form_class = CategoryCreateForm
    template_name = 'userAdmin/category-create.html'
    success_url = reverse_lazy('userAdmin:category_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Создание товара'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class CategoryAdminUpdateView(UpdateView):
    model = ProductsCategory
    form_class = CategoryUpdateForm
    template_name = 'userAdmin/category-update-delete.html'
    success_url = reverse_lazy('userAdmin:category_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Редактирование категории'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # При применении скидки в такой реализации, невозможно вернуть цену путём отмены скидки на категорию
    # Скидку необходимо включать в таблицу категорий в БД
    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.products_set.update(price=F('price') * (1 - discount / 100))
        return super().form_valid(form)


class CategoryAdminDeleteView(DeleteView):
    model = ProductsCategory
    template_name = 'userAdmin/category-update-delete.html'
    success_url = reverse_lazy('userAdmin:category_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# Отображение и редактирование заказов
class OrdersAdminListView(LoginRequiredMixin, ListView):
    model = Order
    extra_context = {'title': 'Админ-панель - Заказы'}
    template_name = 'userAdmin/order-list.html'

    def get_queryset(self):
        return Order.objects.select_related()


class OrdersAdminCreateView(CreateView):
    model = Order
    form_class = OrdersCreateForm
    template_name = 'userAdmin/order-create.html'
    success_url = reverse_lazy('userAdmin:orders_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Создание заказа'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class OrdersAdminUpdateView(UpdateView):
    model = Order
    form_class = OrdersUpdateForm
    template_name = 'userAdmin/order-update-delete.html'
    success_url = reverse_lazy('userAdmin:orders_read')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'Админ-панель - Редактирование заказа'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class OrdersAdminDeleteView(DeleteView):
    model = Order
    template_name = 'userAdmin/category-update-delete.html'
    success_url = reverse_lazy('userAdmin:orders_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_staff))

userAdmin/templates/userAdmin/category-list.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID категории</th>
                                <th>Наименование</th>
                                <th>Описание</th>
                                <th>Статус активности</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID категории</th>
                                <th>Наименование</th>
                                <th>Описание</th>
                                <th>Статус активности</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in productscategory_list %}
                                <tr>
                                    <td><a href="{% url 'userAdmin:category_update' category.id %}"
                                           style="color: dodgerblue">{{ category.id }}</a></td>
                                    <td>{{ category.name }}</td>
                                    <td>{{ category.description }}</td>

                                    {% if category.is_active %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'userAdmin:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

userAdmin/templates/userAdmin/category-update-delete.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование категории | {{ productscategory.name }}</h1>
            <div class="card-body">
                <form action="{% url 'userAdmin:category_update' productscategory.id %}" method='post'
                      enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Статус
                                    активности</label>
                                {{ form.is_active }}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка, %</label>
                                {{ form.discount }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <form action=" {% url 'userAdmin:category_delete' productscategory.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">

                <ul>
                    {% for field, error_list in form.errors.items %}
                        {% for error in error_list %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

        {% endif %}
    </main>
{% endblock %}

userAdmin/templates/userAdmin/order-list.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Заказы</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Заказы
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID заказа</th>
                                <th>Имя пользователя</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Статус</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID заказа</th>
                                <th>Имя пользователя</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Статус</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for order in order_list %}
                                <tr>
                                    <td><a href="{% url 'userAdmin:orders_update' order.id %}"
                                           style="color: dodgerblue">{{ order.id }}</a></td>
                                    <td>{{ order.user }}</td>
                                    <td>{{ order.created|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.updated|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.get_status_display }}</td>

                                    {% if order.is_active %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'userAdmin:orders_create' %}">
                        <button class="btn btn-success">Создать заказ</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

userAdmin/templates/userAdmin/order-update-delete.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование заказа № {{ order.id }}</h1>
            <div class="card-body">
                <form action="{% url 'userAdmin:orders_update' order.id %}" method='post'
                      enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.status.id_for_label }}">Статус заказа</label>
                                {{ form.status }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.is_active.id_for_label }}">Статус
                                    активности</label>
                                {{ form.is_active }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.user.id_for_label }}">Пользователь</label>
                            {{ form.user }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <form action=" {% url 'userAdmin:orders_delete' order.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">

                <ul>
                    {% for field, error_list in form.errors.items %}
                        {% for error in error_list %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

        {% endif %}
    </main>
{% endblock %}

userAdmin/templates/userAdmin/products-list.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Товары</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Товары
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID товара</th>
                                <th>Наименование</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Статус активности</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID товара</th>
                                <th>Наименование</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Статус активности</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in products_list %}
                                <tr>
                                    <td><a href="{% url 'userAdmin:products_update' product.id %}"
                                           style="color: dodgerblue">{{ product.id }}</a></td>
                                    <td>{{ product.name }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.category }}</td>

                                    {% if product.is_active %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'userAdmin:products_create' %}">
                        <button class="btn btn-success">Создать товар</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}