geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from geekshop import settings
from django.conf.urls.static import static

from products.views import ProductsIndexView

urlpatterns = [
    path('', ProductsIndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('userAdmin/', include('userAdmin.urls', namespace='userAdmin')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

orders/urls.py
from django.urls import path
from geekshop import settings
from django.conf.urls.static import static

from orders.views import OrdersList, OrderItemsCreate, OrderRead, OrderUpdate, OrderDelete, \
    order_forming_complete, get_product_price

app_name = 'orders'

urlpatterns = [
    path('', OrdersList.as_view(), name='OrdersList'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='OrderItemsCreate'),
    path('read/<int:pk>/', OrderRead.as_view(), name='OrderRead'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='OrderUpdate'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='OrderDelete'),
    path('product/<int:pk>/price/', get_product_price, name='get_product_price'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserCreateView, profile, verify
# from users.views import UserProfileView

app_name = 'users'

urlpatterns = [
    path('', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('profile/', profile, name='profile'),
    # path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

orders/models.py
from django.conf import settings
from django.db import models

from products.models import Products


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='пользователь'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='создан'
    )

    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='обновлен'
    )
    status = models.CharField(
        max_length=3,
        choices=ORDER_STATUS_CHOICES,
        default=FORMING,
        verbose_name='статус'
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='активен'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.id}'

    def delete(self):
        items = self.order_items.select_related('product')
        for item in items:
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    def get_total_cost(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='order_items',
        verbose_name='заказ'
    )
    product = models.ForeignKey(
        Products,
        on_delete=models.CASCADE,
        verbose_name='продукт')

    quantity = models.PositiveIntegerField(
        default=0,
        verbose_name='количество'
    )

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    def __str__(self):
        return self.product.name

orders/forms.py
from django import forms

from basket.models import Basket
from orders.models import Order, OrderItem
from products.models import Products


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            self.fields['product'].queryset = Products.get_items()
            field.widget.attrs['class'] = 'form-control'

    # Очищает корзину пльзователя при сохранении формы заказа
    # def save(self, commit=True):
    #     instance = super(OrderItemForm, self).save(commit=False)
    #     basket_items = Basket.objects.filter(user=self.user)
    #     if commit:
    #         basket_items.delete()
    #     return instance

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.db.models.signals import pre_save, pre_delete

from basket.models import Basket
from orders.forms import OrderItemForm
from orders.models import Order, OrderItem
from products.models import Products


class OrdersList(LoginRequiredMixin, ListView):
    model = Order
    extra_context = {'title': 'GeekShop - Заказы'}
    template_name = 'orders/user-order-list.html'

    def get_queryset(self):
        return Order.objects.select_related('user').filter(user=self.request.user, is_active=True)


class OrderItemsCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:OrdersList')
    template_name = 'orders/order-form.html'

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        order_formset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = order_formset(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user).select_related()
            if len(basket_items):
                order_formset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items) + 1)
                formset = order_formset()
                for i, form in enumerate(formset.forms):
                    if i == len(formset.forms) - 1:
                        break
                    else:
                        form.initial['product'] = basket_items[i].product
                        form.initial['quantity'] = basket_items[i].quantity
                        form.initial['price'] = basket_items[i].product.price
                basket_items.delete()
            else:
                formset = order_formset()

        data['order_items'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:OrdersList')

    def get_context_data(self, **kwargs):
        data = super(OrderUpdate, self).get_context_data(**kwargs)
        order_formset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            data['order_items'] = order_formset(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = order_formset(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

            data['order_items'] = formset

            return data

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderUpdate, self).form_valid(form)


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('orders:OrdersList')
    template_name = 'orders/order-confirm-delete.html'


class OrderRead(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/order-details.html'

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)

        items = OrderItem.objects.select_related('order').filter(order=kwargs['object'].id)
        total_quantity = sum(list(map(lambda x: x.quantity, items)))
        total_cost = sum(list(map(lambda x: x.quantity * x.product.price, items)))
        product_type_quantity = len(items)

        context = {
            **context,
            'title': 'заказ/просмотр',
            'order_total_quantity': total_quantity,
            'order_total_cost': total_cost,
            'order_product_type_quantity': product_type_quantity,
        }
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('orders:OrdersList'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Products.objects.get(pk=int(pk))
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

orders/templates/orders/admin-order-list.html
{% extends 'userAdmin/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Заказы</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Заказы
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID заказа</th>
                                <th>Имя пользователя</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Статус</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID заказа</th>
                                <th>Имя пользователя</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Статус</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for order in order_list %}
                                <tr>
                                    <td><a href="{#% url 'orders:update_order' order.id %#}"
                                           style="color: dodgerblue">{{ order.id }}</a></td>
                                    <td>{{ order.user }}</td>
                                    <td>{{ order.created|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.updated|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.get_status_display }}</td>

                                    {% if order.is_active %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{#% url 'orders:CreateOrder' %#}">
                        <button class="btn btn-success">Создать заказ</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

orders/templates/orders/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|title }}
       {% endblock %}
   </title>
   {% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
   {% endblock %}
   {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/orders_scripts.js' %}"></script>
   {% endblock %}
</head>
<body>
  <div class="order_container">
       {% block content %}

       {% endblock %}

  </div>
</body>
</html>

orders/templates/orders/order-confirm-delete.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">
                            Удалить заказ № {{ object.pk }}</h3>
                        </div>
                        <div class="card-body">
                            <div>заказчик: {{ user.last_name }} {{ user.first_name }} </div>
                            <div>обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
                            <div>статус: {{ object.get_status_display }}</div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <form action="{% url 'orders:OrderDelete' object.pk %}" method="post">
                                    {% csrf_token %}
                                    <input class="btn btn-danger" type="submit" value="удалить">
                                </form>
                                <button class="btn btn-secondary">
                                    <a href="{% url 'orders:OrdersList' %}" style="color: #ffffff">отмена</a>
                                </button>
                            </div>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

orders/templates/orders/order-details.html
{% extends "products/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% include 'orders/includes/inc-order-summary.html' %}
        <div class="col-lg-9">
            <div class="row">
                {% for item in object.order_items.select_related %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="{{ item.product.image.url }}"
                                     alt="">
                            </a>
                            <div class="card-body"
                                 style="display: flex;flex-direction: column;justify-content: space-between;">
                                <h4 class="card-title">
                                    <a href="#">{{ item.product.name }}</a>
                                </h4>
                                <div class="my-card-style">
                                    <h5>Цена {{ item.product.price }} руб.</h5>
                                    <p class="card-text">Количество {{ item.quantity }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include 'orders/includes/inc-order-actions.html' %}
    </div>
{% endblock %}

orders/templates/orders/order-form.html
{% extends "products/base.html" %}
{% load static %}
{% load cache %}

{% block js %}
    <script src="{% static 'js/orders.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        {% include 'orders/includes/inc-order-summary.html' %}
        <div class="order_form">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <table class="table">
                    {{ order_items.management_form }}
                    {% for form in order_items.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                        {{ field.label|capfirst }}
                                    </th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr class="formset_row">
                            {% for field in form.visible_fields %}
                                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}

                                    {% if field.name != 'price' %}
                                        {% if field.name == 'product' %}
                                            {% cache 3600 orderitemform_product field.value %}
                                                {{ field }}
                                            {% endcache %}
                                        {% else %}
                                            {{ field }}
                                        {% endif %}

                                    {% else %}
                                        {% if field.value %}
                                            <span class="order_items-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб.
                                        {% endif %}
                                    {% endif %}

                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>

                <button value="сохранить" type="submit" class="btn btn-default btn-round form-control last">
                    сохранить
                </button>

                {% include 'orders/includes/inc-order-actions.html' %}
            </form>
        </div>
    </div>
{% endblock %}

orders/templates/orders/user-order-list.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Ваши заказы</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Заказы
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID заказа</th>
                            <th>Имя пользователя</th>
                            <th>Создан</th>
                            <th>Обновлен</th>
                            <th>Статус заказа</th>
                            <th>Статус активности</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID заказа</th>
                            <th>Имя пользователя</th>
                            <th>Создан</th>
                            <th>Обновлен</th>
                            <th>Статус заказа</th>
                            <th>Статус активности</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for order in order_list %}
                            <tr>
                                <td><a href="{% url 'orders:OrderRead' order.id %}"
                                       style="color: dodgerblue">{{ order.id }}</a></td>
                                <td>{{ order.user }}</td>
                                <td>{{ order.created|date:"Y-m-d H:i:s" }}</td>
                                <td>{{ order.updated|date:"Y-m-d H:i:s" }}</td>
                                <td>{{ order.get_status_display }}</td>

                                {% if order.is_active %}
                                    <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                {% else %}
                                    <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                {% endif %}
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'orders:OrderItemsCreate' %}">
                    <button class="btn btn-success">Создать заказ</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}