geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from geekshop import settings
from django.conf.urls.static import static

from products.views import ProductsIndexView

urlpatterns = [
    path('', ProductsIndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('userAdmin/', include('userAdmin.urls', namespace='userAdmin')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserCreateView, profile, verify
# from users.views import UserProfileView

app_name = 'users'

urlpatterns = [
    path('', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('profile/', profile, name='profile'),
    # path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

users/models.py
import hashlib
import random
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    def is_activation_key_expired(self):
        return True if now() > self.activation_key_expires else False

    is_active = models.BooleanField(default=True)

    image = models.ImageField(upload_to='users_images', blank=True)
    activation_key = models.CharField(
        max_length=123,
        default=hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:16]
    )
    activation_key_expires = models.DateTimeField(
        default=(now() + timedelta(hours=48))
    )


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(User, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name='тэги', max_length=128, blank=True)
    about_me = models.TextField(verbose_name='о себе', max_length=256, blank=True)
    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.core.mail import send_mail
from django.urls import reverse

from geekshop import settings
from users.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = (
            'username',
            'password'
        )


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите логин',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите адрес эл. почты',
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите фамилию',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Повторите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()

        # making and sending confirm message to new user
        verify_link = reverse('users:verify', args=[user.email, user.activation_key])
        title = f'Подтверждение учётной записи GeekShop'
        message = f'Для подтверждения учётной записи {user.username} на сайте {settings.DOMAIN_NAME}, ' \
                  f'перейдите по следующей ссылке:\n<a href="{verify_link}">Активировать</a>'
        send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'readonly': True,
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }), required=False)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'image',
            'username',
            'email',
        )


class UserProfileFormExtended(forms.ModelForm):

    # tagline = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    # }), required=False)
    #
    # about_me = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    # }), required=False)

    # gender = forms.ChoiceField(widget=forms.TextInput(attrs={
    #     'class': 'form-control py-4',
    # }), required=False)

    class Meta:
        model = UserProfile
        fields = (
            'tagline',
            'about_me',
            'gender',
        )

    def __init__(self, *args, **kwargs):
        super(UserProfileFormExtended, self).__init__(*args, **kwargs)

        user = UserProfile.objects.get(id=kwargs['instance'].id)
        self.initial['tagline'] = user.tagline
        self.initial['about_me'] = user.about_me
        self.initial['gender'] = user.gender

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['required'] = False

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm, UserProfileFormExtended
from users.models import User


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    authentication_form = UserLoginForm
    extra_context = {'title': 'GeekShop - Авторизация'}


class UserCreateView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'GeekShop - Регистрация'
        return context


class UserLogoutView(LoginRequiredMixin, LogoutView):
    pass


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, files=request.FILES, data=request.POST)
        form_extended = UserProfileFormExtended(instance=request.user.userprofile, data=request.POST)
        if form.is_valid() and form_extended.is_valid():
            form.save()
            form_extended.save()
            messages.success(request, 'Данные успешно обновлены')
    else:
        form = UserProfileForm(instance=request.user)
        form_extended = UserProfileFormExtended(instance=request.user.userprofile)
    context = {
        'title': 'GeekShop - Личный кабинет',
        'form': form,
        'form_extended': form_extended,
    }
    return render(request, 'users/profile.html', context)


def verify(request, email, activation_key):
    user = User.objects.get(email=email)
    error_message = ''

    try:
        if user.activation_key == activation_key and user.is_activation_key_expired() is False:
            user.is_active = True
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        elif user.activation_key != activation_key:
            error_message = 'Ключ активации указан неверно'
        elif user.is_activation_key_expired():
            error_message = 'Время действия ключа активации истекло'

        return render(request, 'users/verification.html', context={'error_message': error_message})
    except Exception as err:
        print(f'Error activation user: {err.args}')
        return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if form.errors or messages %}
                        <div class="alert
                        {% if form.errors %} alert-warning {% else %} alert-success {% endif %}
                        alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">

                            {% if form.errors %}
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            {% else %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% endif %}

                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}

                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                {#                                {{ form.as_p }}#}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                        пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт?
                                Зарегистрируйся!</a></div>
                            <div class="small">
                                <a href="{% url 'social:begin' 'vk-oauth2' %}">Вход через ВК</a>
{#                                {% if request.GET.next %}#}
{#                                    <input type="hidden" name="next" value="{{ request.GET.next }}">#}
{#                                {% endif %}#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                {% if messages %}

                    <div class="alert alert-success alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">

                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}

                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form_extended.tagline.id_for_label }}">Тэги</label>
                            {{ form_extended.tagline }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form_extended.gender.id_for_label }}">Пол</label>
                            {{ form_extended.gender }}
                        </div>
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form_extended.about_me.id_for_label }}">Обо мне</label>
                            {{ form_extended.about_me }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% include 'basket/basket.html' %}
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}

                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">

                            <ul>
                            {% for field, error_list in form.errors.items %}
                                {% for error in error_list %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                            </ul>

                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                    {% endif %}

                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.first_name.id_for_label }}">Имя</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                            пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                            почты</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.password1.id_for_label }}">Пароль</label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                пароля</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/verification.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}

  {% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
  {% else %}
    <h3>Верификация не пройдена.</h3>
      {{ error_message }}
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'products:index' %}" class="">на главную</a>
  </button>

{% endblock %}