basket/urls.py
from django.urls import path
from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from geekshop import settings
from django.conf.urls.static import static

from products.views import ProductsIndexView

urlpatterns = [
    path('', ProductsIndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('userAdmin/', include('userAdmin.urls', namespace='userAdmin')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

orders/urls.py
from django.urls import path
from geekshop import settings
from django.conf.urls.static import static

from orders.views import OrdersList, OrderItemsCreate, OrderRead, OrderUpdate, OrderDelete, \
    order_forming_complete, get_product_price

app_name = 'orders'

urlpatterns = [
    path('', OrdersList.as_view(), name='OrdersList'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='OrderItemsCreate'),
    path('read/<int:pk>/', OrderRead.as_view(), name='OrderRead'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='OrderUpdate'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='OrderDelete'),
    path('product/<int:pk>/price/', get_product_price, name='get_product_price'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('<int:category_id>/', ProductsListView.as_view(), name='products'),
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserLogoutView, UserCreateView, profile, verify
# from users.views import UserProfileView

app_name = 'users'

urlpatterns = [
    path('', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserCreateView.as_view(), name='registration'),
    path('profile/', profile, name='profile'),
    # path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

products/models.py
from django.db import models


class ProductsCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(blank=False, default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Products(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductsCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(blank=False, default=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


    def __str__(self):
        return f'{self.name}'

    @staticmethod
    def get_items():
        # return Products.objects.filter(is_active=True).order_by('category', 'name')
        return Products.objects.order_by('category', 'name')

products/views.py
from django.core.cache import cache

from geekshop import settings
from products.models import Products, ProductsCategory
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


class ProductsIndexView(TemplateView):
    template_name = 'products/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['title'] = 'GeekShop'
        return context


class ProductsListView(ListView):
    model = Products
    context_object_name = 'products'
    paginate_by = 6
    template_name = 'products/products.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'GeekShop - Каталог'
        context['ProductsCategory'] = self.get_categories()
        return context

    def get_queryset(self):
        if 'category_id' in self.kwargs:
            chosen_category_id = self.kwargs['category_id']
        else:
            chosen_category_id = None
        if settings.LOW_CACHE:
            if chosen_category_id:
                key = f'products_{chosen_category_id}'
                products = cache.get(key)
                if products is None:
                    products = Products.objects.filter(category_id=chosen_category_id, is_active=True).order_by('id')
                    cache.set(key, products)
            else:
                key = 'products'
                products = cache.get(key)
                if products is None:
                    products = Products.objects.filter(is_active=True).order_by('id')
                    cache.set(key, products)

        else:
            if not chosen_category_id:
                products = Products.objects.filter(is_active=True).order_by('id')
            else:
                products = Products.objects.filter(category_id=chosen_category_id, is_active=True).order_by('id')

        return products

    @staticmethod
    def get_categories():
        if settings.LOW_CACHE:
            key = 'categories'
            categories = cache.get(key)
            if categories is None:
                categories = ProductsCategory.objects.all()
                cache.set(key, categories)
            return categories
        else:
            return ProductsCategory.objects.all()


# Функция для отображения запроса к БД
def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductsCategory)
def product_products_category_is_active_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.products_set.update(is_active=True)
        else:
            instance.products_set.update(is_active=False)

        # db_profile_by_type(sender, 'UPDATE', connection.queries)

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i
                            class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
                    {#                            <i class="fas fa-user-circle"></i>#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    {% if user.is_staff or user.is_superuser %}#}
                    {#                                            <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'userAdmin:index' %}">#}
                    {#                            <i class="fas fa-users-cog"></i>#}
                    {#                        </a>#}
                    {#                    </li>#}
                    {#                    {% endif %}#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i#}
                    {#                                class="fas fa-sign-out-alt"></i></a>#}
                    {#                    </li>#}
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-expanded="false" style="background-color: inherit; border-color: transparent; padding: 8px">
                            {{ user.username }}
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">
                                    <i class="fas fa-user-circle"></i>
                                    Профиль
                                </a>
                            </li>
                            {% if user.is_staff or user.is_superuser %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'userAdmin:index' %}">
                                        <i class="fas fa-users-cog"></i>
                                        Админ панель
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'orders:OrdersList' %}">
                                    {#                                    <i class="bi bi-truck"></i>#}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-truck" viewBox="0 0 16 16">
                                        <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                    </svg>
                                    Заказы
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    <i class="fas fa-sign-out-alt"></i>
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/basket.js' %}"></script>

{% block js %}

{% endblock %}

</body>

</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in ProductsCategory %}
                        <a href="{% url 'products:products' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }},00 руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success" href="{% url 'basket:basket_add' product.id %}">Отправить
                                        в корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="
                            {% if page_obj.has_previous %}
                                ?page={{ page_obj.previous_page_number }}
                            {% else %}
                                #
                            {% endif %}"
                               tabindex="-1" aria-disabled="true">
                                Предыдущая
                            </a>
                        </li>

                        {% for page in paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="
                           {% if page_obj.has_next %}
                                ?page={{ page_obj.next_page_number }}
                           {% else %}
                                #
                           {% endif %}">
                                Следующая
                            </a>
                        </li>

                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}